### ISSUE TITLE
Tipp: let the Crops-Shapes grow with the Crops

### ISSUE THREAD

**Issue by DancerVlt69** [Zuiron/Photosynthesis#20]
Not an Issue but a Tipp 
![image](https://user-images.githubusercontent.com/49952690/218236963-70cf9c00-8cb1-4730-87fc-8fb1e5724e5d.png)
![image](https://user-images.githubusercontent.com/49952690/218236970-931085b8-85b1-4abc-bd9d-e0a9c42af025.png)
![image](https://user-images.githubusercontent.com/49952690/218236974-c491a039-fb1f-4389-9437-1b3feabe67c8.png)

for the AppletreeCops:

` Block.createCuboidShape ( 4.0D, 13.0D, 4.0D, 12.0D, 16.0D, 12.0D),

  Block.createCuboidShape ( 4.0D, 10.0D, 4.0D, 12.0D, 16.0D, 12.0D),

  Block.createCuboidShape ( 4.0D, 7.0D, 4.0D, 12.0D, 16.0D, 12.0D),

  Block.createCuboidShape ( 3.0D, 4.0D, 3.0D, 13.0D, 16.0D, 13.0D)
  `
  reverse because the cops growing up side down

**Comment by DancerVlt69** [comment]
Ah, and the apples growing extremely fast!

**Comment by Zuiron** [comment]
thanks :D yes growth rate is TODO :P
