### ISSUE TITLE
suggestion: add food spoilage and greenhouse block

### ISSUE THREAD

**Issue by gundami** [Zuiron/Photosynthesis#218]
1. food will spoilage after a few days
2. greenhouse allow growing plants in any season

**Comment by Zuiron** [comment]
1. I think theres already a mod that does that. pretty sure i saw that somewhere.
2. I will be making an expansion mod for photosynthesis which is more "techy" which will include a way to grow crops outside seasons. ive seen other mods adding a single block like a greenhouse glass block but i think thats just way too simple. so im gonna go the hard route and imo better route :P
