### ISSUE TITLE
livestock traders prevent many modded villager types from spawning

### ISSUE THREAD

**Issue by recursedev54** [Zuiron/Photosynthesis#224]
Using photosynthesis 0.19, Villagers plus 3.0 (forge), forge 47.1.3-1.20.1 and any version of synatra connector and forgified fabric api.
Livestock traders will replace villagerplus villageres when you place villagerplus workstations. this also happens for domestication innovation. I have not tested with fabric mods that add new villager type, but it seems to occur for most every forge mod.

**Comment by Zuiron** [comment]
perhaps post a bug report in forgified fabric api.

since your bug occurs when using "not native fabric".
