### ISSUE TITLE
add option to disable/enable spawning of added mobs

### ISSUE THREAD

**Issue by Zuiron** [Zuiron/Photosynthesis#226]
title.

**Comment by recursedev54** [comment]
including an option to disable villagers turning into livestock traders would be a really amazing qol to allow compatibility with certain other modded villager workstations

**Comment by Zuiron** [comment]
what do you mean? they should only turn into livestock traders if there is a cutting board.

**Comment by recursedev54** [comment]
some modded villagers turn into livestock traders when at their own mod's workstation
