### ISSUE TITLE
Conquest Reforged incompatibility

### ISSUE THREAD

**Issue by Beowulfchk** [Zuiron/Photosynthesis#236]
Has some issue with vanilla beetroot? I removed this mod and my game would finally load.
[crash-2024-05-24_15.55.51-client.txt](https://github.com/Zuiron/Photosynthesis/files/15439350/crash-2024-05-24_15.55.51-client.txt)
[latest.log](https://github.com/Zuiron/Photosynthesis/files/15439356/latest.log)

**Comment by Zuiron** [comment]
an issue with reforged. closing.
