### ISSUE TITLE
Make snow melt when in any season other than winter and in a warmer biome.

### ISSUE THREAD

**Issue by Mr-iMikeyyy** [Zuiron/Photosynthesis#240]
Hey guys, I'm huge fan of the mod. It's everything I've been looking for and fits very well with all my other mods. I'm having a slight issue. the snow doesn't seem to melt right. I went exploring during the winter and it passed into spring and by the time I got back it was summer. When I got back I noticed that the snow persisted all the way through summer and autumn. It would be great if there was a check for spring having mild snow melting, and summer having definitely snow melting behavior when in warm biomes.

**Comment by Zuiron** [comment]
Hmm what biome was it where it didn't melt? Haven't experienced this myself. Might be a bug. Will try to solve of course but need more info. Thanks

**Comment by Mr-iMikeyyy** [comment]
My base is in the forest biome, just booted it back up and you can see snow in autumn left over from last winter. 
![2024-10-13_19 29 26](https://github.com/user-attachments/assets/95f1ac09-6a6d-478f-a5db-af34ec5e46d5)

**Comment by Mr-iMikeyyy** [comment]
I have something to add, I am using a mod called "Snow! Real Magic!" which makes snow accumulate if it is snowing. https://modrinth.com/mod/snow-real-magic . It might be the two are incompatible.

**Comment by Zuiron** [comment]
yeah been testing for awhile now, snow melts as should be. so has to be mod incompatability jep.

**Comment by Mr-iMikeyyy** [comment]
It was a mod incompatibility, I've removed the incompatible mod and everything works as it should.

My sincere apologies for wasting your time trying to hunt it.

**Comment by Zuiron** [comment]
no problem, no need to apologise :D
