### ISSUE TITLE
Crash on crop growth

### ISSUE THREAD

**Issue by twistedintel** [Zuiron/Photosynthesis#244]
Server crashes on crop growth when during sleeping.

May be due to sleep mod installed on server.
[crash-2024-11-08_11.35.27-server.txt](https://github.com/user-attachments/files/17682283/crash-2024-11-08_11.35.27-server.txt)

**Comment by Zuiron** [comment]
probably sleep mod incompatability yeah. try without the sleep mod and see then.

**Comment by twistedintel** [comment]
Removing the Steve's Realistic Sleep mod seems to have solved the crash. Shame though, I like the mod because it ticks through the night instead of skipping. Maybe consider future compatability or inclusion of similar mechanics?

Loving what you have so far. Looking forward to being able to use in a mod pack in future once you reach a release state.

**Comment by Zuiron** [comment]
yeah ok. good it was solved. well i cant make it compatible no idea why its trying to increase age on crops this way (looking at the error). well glad its solved anyway :)
