### ISSUE TITLE
My players can't create Crop Sticks to start mutating plants

### ISSUE THREAD

**Issue by Mr-iMikeyyy** [Zuiron/Photosynthesis#245]
Per the title, we aren't seeing any way of crafting the crop sticks. Are they generated automatically somehow? Should there be a crafting recipe?

**Comment by Zuiron** [comment]
hmmm, did i really forget to add a recipe for the crop sticks ? xD

**Comment by Mr-iMikeyyy** [comment]
Lol, I'm able to give the cropsticks to myself as op so I know the item exists. I've been messing around with sticks, planks and fences to see if I could guess it somehow with no luck.

**Comment by Zuiron** [comment]
do you have REI installed ?

**Comment by Mr-iMikeyyy** [comment]
Yes, I can see all the mutation recipes, but no crafting for the sticks themselves.

**Comment by Zuiron** [comment]
okay, i will look into it tomorrow and make a new update

**Comment by Zuiron** [comment]
https://modrinth.com/mod/photosynthesis/version/1.20.1-0.0.24
